{% set name = "prolif" %}
{% set version = "2.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prolif-{{ version }}.tar.gz
  sha256: e0951b23e2144328917496efd65c4d8f7c821045a8beaf5fe86f3706c648acd0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - rdkit
  run:
    - python >={{ python_min }}
    - pandas >=1.0.0
    - numpy >=1.13.3
    - scipy >=1.3.0
    - mdanalysis >=2.2.0
    - tqdm
    - rdkit >=2021.03.1
    - multiprocess
    - dill

test:
  imports:
    - prolif
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest>=6.1.2
    - ipython
    - py3Dmol
    - matplotlib>=3.5
    - python {{ python_min }}
  source_files:
    - tests/

about:
  home: https://github.com/chemosim-lab/ProLIF
  summary: Protein-Ligand Interaction Fingerprints
  dev_url: https://github.com/chemosim-lab/ProLIF/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cbouy
