{% set name = "prolif" %}
{% set version = "2.0.0.post0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prolif-{{ version }}.tar.gz
  sha256: d57a354e0481b6b6842325943d0ed81f3da50f9c429ec2ed139568bb09c116b1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - rdkit
  run:
    - python >=3.8
    - pandas >=1.0.0
    - numpy >=1.13.3
    - scipy >=1.3.0
    - mdanalysis >=2.2.0
    - tqdm
    - rdkit >=2021.03.1

test:
  imports:
    - prolif
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest>=6.1.2
  source_files:
    - tests/

about:
  home: https://github.com/chemosim-lab/ProLIF
  summary: Protein-Ligand Interaction Fingerprints
  dev_url: https://github.com/chemosim-lab/ProLIF/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - cbouy
